### ISSUE TITLE
Got "Overflow detected" at presto-orc with zstd

### ISSUE THREAD

**Issue by miniway** [airlift/aircompressor#122]
I got "Overflow detected" at creating an ORC file through presto-orc from large input data so I could not easily reproduce. That might be because I'm using  a bit old version of presto 317. 
```
java.lang.IllegalStateException: Overflow detected
	at io.airlift.compress.zstd.Util.checkState(Util.java:59)
	at io.airlift.compress.zstd.BitOutputStream.close(BitOutputStream.java:85)
	at io.airlift.compress.zstd.HuffmanCompressor.compressSingleStream(HuffmanCompressor.java:130)
	at io.airlift.compress.zstd.HuffmanCompressor.compress4streams(HuffmanCompressor.java:75)
	at io.airlift.compress.zstd.ZstdFrameCompressor.encodeLiterals(ZstdFrameCompressor.java:333)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compressBlock(ZstdFrameCompressor.java:224)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compressFrame(ZstdFrameCompressor.java:172)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compress(ZstdFrameCompressor.java:145)
	at io.airlift.compress.zstd.ZstdCompressor.compress(ZstdCompressor.java:45)
	at io.prestosql.orc.OrcOutputBuffer.writeChunkToOutputStream(OrcOutputBuffer.java:445)
	at io.prestosql.orc.OrcOutputBuffer.flushBufferToOutputStream(OrcOutputBuffer.java:425)
	at io.prestosql.orc.OrcOutputBuffer.close(OrcOutputBuffer.java:146)
	at io.prestosql.orc.stream.LongOutputStreamV2.close(LongOutputStreamV2.java:739)
	at io.prestosql.orc.writer.SliceDirectColumnWriter.close(SliceDirectColumnWriter.java:139)
	at io.prestosql.orc.writer.SliceDictionaryColumnWriter.close(SliceDictionaryColumnWriter.java:324)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
	at io.prestosql.orc.OrcWriter.bufferStripeData(OrcWriter.java:369)
	at io.prestosql.orc.OrcWriter.flushStripe(OrcWriter.java:331)
	at io.prestosql.orc.OrcWriter.close(OrcWriter.java:444)
```

But I have  a question on the these two lines as I'm not familiar with the zstd. If `currentAddress < outputLimit` is expected at line 85, `currentAddress = outputLimit` looks confusing at line 73. Just raising an exception here might be less confusing. 

https://github.com/airlift/aircompressor/blob/master/src/main/java/io/airlift/compress/zstd/BitOutputStream.java#L73

https://github.com/airlift/aircompressor/blob/master/src/main/java/io/airlift/compress/zstd/BitOutputStream.java#L85

**Comment by miniway** [comment]
0.15 doesn't raise this exception but 0.18 does. Is related to  https://github.com/airlift/aircompressor/commit/cabfa6593244b9d7fcb1765eb06df4a1d860bf51 ?

**Comment by findepi** [comment]
Thanks @miniway for the report!
Can you perhaps try to reproduce this in a synthetic way, eg using tpch data as the input?
That would also help verify the problem still exists in the latest release.

**Comment by miniway** [comment]
Unfortunately I could not easily reproduce the issue, but my gut feeling is it doesn't seem to happen at 0.15 but it happens rarely at 0.18

**Comment by dongjoon-hyun** [comment]
Hi, All. Apache ORC community also is blocked by this issue. This causes UT failures consistently.
Apache ORC community has been using 0.16 without this issue. New 0.17 and 0.18 seems to have this issue.
```
Caused by: java.lang.IllegalStateException: Overflow detected
	at io.airlift.compress.zstd.Util.checkState(Util.java:59)
	at io.airlift.compress.zstd.BitOutputStream.close(BitOutputStream.java:85)
	at io.airlift.compress.zstd.HuffmanCompressor.compressSingleStream(HuffmanCompressor.java:130)
	at io.airlift.compress.zstd.HuffmanCompressor.compress4streams(HuffmanCompressor.java:75)
	at io.airlift.compress.zstd.ZstdFrameCompressor.encodeLiterals(ZstdFrameCompressor.java:333)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compressBlock(ZstdFrameCompressor.java:224)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compressFrame(ZstdFrameCompressor.java:172)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compress(ZstdFrameCompressor.java:145)
	at io.airlift.compress.zstd.ZstdCompressor.compress(ZstdCompressor.java:45)
	at org.apache.orc.impl.AircompressorCodec.compress(AircompressorCodec.java:68)
	at org.apache.orc.impl.OutStream.spill(OutStream.java:290)
	at org.apache.orc.impl.OutStream.write(OutStream.java:263)
	at org.apache.orc.impl.SerializationUtils.writeLongBE(SerializationUtils.java:840)
	at org.apache.orc.impl.SerializationUtils.unrolledBitPackBytes(SerializationUtils.java:674)
	at org.apache.orc.impl.SerializationUtils.unrolledBitPack32(SerializationUtils.java:644)
	at org.apache.orc.impl.SerializationUtils.writeInts(SerializationUtils.java:497)
	at org.apache.orc.impl.RunLengthIntegerWriterV2.writeDirectValues(RunLengthIntegerWriterV2.java:370)
	at org.apache.orc.impl.RunLengthIntegerWriterV2.writeValues(RunLengthIntegerWriterV2.java:174)
	at org.apache.orc.impl.RunLengthIntegerWriterV2.write(RunLengthIntegerWriterV2.java:804)
	at org.apache.orc.impl.writer.IntegerTreeWriter.writeBatch(IntegerTreeWriter.java:87)
	at org.apache.orc.impl.writer.StructTreeWriter.writeRootBatch(StructTreeWriter.java:56)
	at org.apache.orc.impl.WriterImpl.addRowBatch(WriterImpl.java:704)
	... 60 more
```

**Comment by martint** [comment]
Thanks for narrowing down the issue to that commit. I’ll take a look soon.

**Comment by martint** [comment]
Also, do you have a data set that reproduces it consistently? I’d like to investigate whether there’s a bug elsewhere that is being surfaced by that change.

**Comment by martint** [comment]
The formula matches the one in the reference implementation, so this must be a bug somewhere else. It would help a lot to have a dataset that reproduces the problem.

> #define ZSTD_COMPRESSBOUND(srcSize)   ((srcSize) + ((srcSize)>>8) + (((srcSize) < (128<<10)) ? (((128<<10) - (srcSize)) >> 11) /* margin, from 64 to 0 */ : 0))

**Comment by dongjoon-hyun** [comment]
Update: Apache ORC upgrades to 0.19 finally. Thanks!

**Comment by melin** [comment]
aircompression 0.20

**Comment by dongjoon-hyun** [comment]
Thank you for reporting, @melin . If you don't mind, could you file a JIRA at https://issues.apache.org/jira/projects/ORC with the above information?

**Comment by martint** [comment]
I've been able to reproduce this locally. I'm investigating.

**Comment by dongjoon-hyun** [comment]
Thank you, @martint !
