### ISSUE TITLE
Implement Hadoop CompressionInputStream resetState

### ISSUE THREAD

**Issue by sertel** [airlift/aircompressor#58]
Hi,

Please remove the below exception. It is ok to reset state that is not existing :)
Otherwise your SnappyCodec will not work with Hadoop's SequenceFile implementation.
```
java.lang.UnsupportedOperationException: resetState not supported for Snappy
	at io.airlift.compress.snappy.HadoopSnappyInputStream.resetState(HadoopSnappyInputStream.java:81)
	at org.apache.hadoop.io.SequenceFile$Reader.seekToCurrentValue(SequenceFile.java:2134)
	at org.apache.hadoop.io.SequenceFile$Reader.getCurrentValue(SequenceFile.java:2217)
	at org.apache.hadoop.mapreduce.lib.input.SequenceFileRecordReader.nextKeyValue(SequenceFileRecordReader.java:78)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:556)
	at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
```

**Comment by sertel** [comment]
The same account for LZO. :(

**Comment by dain** [comment]
This was implemented about a year ago, and I forgot to close the issue. Sorry.
