### ISSUE TITLE
JNI error 

### ISSUE THREAD

**Issue by amerolla** [airlift/aircompressor#85]
I tried running:
java -cp aircompressor-0.12-SNAPSHOT-tests.jar io.airlift.compress.benchmark.CompressionBenchmark

Got the following error:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/openjdk/jmh/runner/options/Options
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:522)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:504)
Caused by: java.lang.ClassNotFoundException: org.openjdk.jmh.runner.options.Options
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by amerolla** [comment]
Is there a dependency I need to add to the pom.xml file?

**Comment by martint** [comment]
You need to use mvn exec to run run from the CLI so that it adds all the dependencies to the classpath. E.g.:

```
mvn exec:exec -Dexec.classpathScope=test -Dexec.executable="$JAVA_HOME/bin/java" -Dexec.args="-XX:+UseG1GC -cp %classpath io.airlift.compress.benchmark.CompressionBenchmark -p algorithm=airlift_lz4 -i 20 -wi 20 -f 10"
```

The options after CompressionBenchmark are standard JMH args, so adjust as necessary to control parameters, warmup/measurement iterations, etc.

**Comment by amerolla** [comment]
Thank you very much Martin, I'm running now.
